### ISSUE TITLE
changing data sources invalidates bookmarks

### ISSUE THREAD

**Issue by vlandham** [vega/voyager#187]
to replicate:

* bookmark some visuals
* verify that bookmarks are present in bookmark menu
* change data source to different data
* open bookmark menu

Book marks are no longer presented or valid

<img width="555" alt="screen shot 2015-09-24 at 3 39 07 pm" src="https://cloud.githubusercontent.com/assets/9369/10088812/70ccaa60-62d2-11e5-9723-2efcdcabf3b7.png">

We should probably start with just clearing bookmarks on data change.

**Comment by domoritz** [comment]
The problem seems to be that we don't link to the data in the vl specs that we store.

**Comment by domoritz** [comment]
They are not invalidated. The bookmarks work if you switch back to the right datasource. 

The problem is that we don't store the dataset with the bookmark. I'm not sure what the cleanest solution is here. One is to store the vl spec and the stats in the bookmarks and load them in vlgroup. The other option is to actually add the state to the vl spec.

I think the first solution is cleaner at this point.
