### ISSUE TITLE
Request for trimming size of build for lib-voyager

### ISSUE THREAD

**Issue by ajainarayanan** [vega/voyager#673]
Thank you so much for re-writing voyager in react and making it open source! Super awesome thing to do!

- [x] Check for duplicate issues
  - Couldn't find any issue that talks about build size for lib voyager for embedding in other projects.
- [x] Describe how to reproduce the bug / the goal of the new feature request
  - **Library Build size**

Right now if I install `datavoyager` from npm it installs the entire project and the `voyager-lib.js` file is 28mb in size. 

I believe the reason for this size is it comes with all the dependencies pre-bundled + unminified. 

I am creating this issue to request to mark certain projects as "external" dependencies in `webpack.config.lib.js` and use webpack's `UglifyJS` to uglify `voyager-lib.js`. For instance, a person who is going to use this are predominantly going  be having `react` and `react-dom` installed. If we could externalize some projects (react based projects) then it would be super helpful to embed datavoyager as a component in other projects.

  - [ ] The other request is to remove the header and footer in the library build as anybody who is going to embed voyager would not require a header and a footer to be attached. 
 
  - [ ] Separate out the css between common and component specific styles since the existing css file modifies nodes like `html, body, h<>tags` that will cause problems in the environment where it will be embedded.

If the contributors of the project agree about externalizing some projects and trimming down library build I would be more than happy to create a PR. This does not change the functionality. Its a change in the build process and the top level app component (exclude header and footer)

**Comment by kanitw** [comment]
Thanks for asking. 

> I am creating this issue to request to mark certain projects as "external" dependencies in `webpack.config.lib.js` and use webpack's `UglifyJS` to uglify `voyager-lib.js`. For instance, a person who is going to use this are predominantly going  be having `react` and `react-dom` installed. If we could externalize some projects (react based projects) then it would be super helpful to embed datavoyager as a component in other projects.

- I think uglifying voyager-lib.js and extracting external dependencies totally make sense. Feel free to submit a PR.  If you want to do so, please also submit a PR to modify [`voyager-electron`](https://github.com/vega/voyager-electron) to make sure it still works with the new lib file. 

> the header and footer in the library build as anybody who is going to embed voyager would not require a header and a footer to be attached. 

- For header and footer, it would be a good option to have, but  it is not always the case.  For example, our voyager-electron app still want the header.   Feel free to submit a _separate_ PR to add a new `VoyagerConfig` option called `showHeader` (which should be `true` in `DEFAULT_VOYAGER_CONFIG`) to to hide header from `<AppRoot>`.  Keep in mind that currently undo, redo, and bookmark modal open actions  are not exposed via API so you may need to submit another PR to add those methods to `Voyager` in `lib-voyager.tsx`. 

> Separate out the css between common and component specific styles since the existing css file modifies nodes like html, body, h<>tags that will cause problems in the environment where it will be embedded.

For component-specific css, we already use `react-css-module` so this shouldn't be a problem.  The main problem is that we globally import `normalize-scss` in `app.scss`.  This can be fixed by applying `normalize-scss`  only to our `.voyager` namespace. I've not investigated how to do that yet, but please feel free to suggest a solution / submit a PR.  

If you want to submit changes for any of these,  please try to fix one thing (or a few highly relevant things) at a time for each PR though so it's easier for us to review.  :) 

cc: @felixcodes

**Comment by ajainarayanan** [comment]
@kanitw Sounds good. Have created PRs for voyager and voyager-electron 
- https://github.com/vega/voyager/pull/678,
- https://github.com/vega/voyager-electron/pull/32

Let me know if I had missed anything.
