### ISSUE TITLE
Add getSpec function to Voyager class

### ISSUE THREAD

**Issue by davidanthoff** [vega/voyager#746]
I'd like to add an API like this to https://github.com/davidanthoff/DataVoyager.jl, the code below is how a user would start and interact with voyager from the julia REPL:
````julia
julia> using DataVoyager, RDatasets

julia> v = dataset("ggplot2", "mpg") |> Voyager()
````
This opens up the voyager UI in an electron window and you can work with it. Now fiddle with the Voyager UI, when you are done, enter the following command on the REPL to save the spec:
````julia
julia> v |> save("myspec.vegalite")
````
All I would need for that is some way to extract the vega-lite spec of the specified view from the ``Voyager`` instance. An added bonus would be if the function would accept a flag whether I want the data to be included or not in the spec.

**Comment by davidanthoff** [comment]
If someone could give me a hint how to start with this, I could try to do a PR. Essentially all I want to add is something like ``setSpec`` (https://github.com/vega/voyager/blob/master/src/lib-voyager.tsx#L90), but the other way around, i.e. ``getSpec`` that returns the currently visible spec. With that, I could really round out the whole julia story for vega-lite and voyager.

**Comment by davidanthoff** [comment]
Bump, would be great if you guys could give me some indication whether this is something you think might make sense or not, and if yes whether that is something you might do or not. So just a little project management update, I guess. I'm just trying to figure out the best roadmap for the packages on the julia side of things.

**Comment by felixcodes** [comment]
Hi @davidanthoff! if I remember correctly, the `selectMainSpec` [selector](https://github.com/vega/voyager/blob/e024766f71a5dc2b1eb19705063843d26ec88d9b/src/selectors/result.ts#L44) should return the Vega-Lite spec of the currently specified view. From there it's a matter of exposing it via the lib-voyager.tsx API. 

I was going to assign this to @abanh206 (he also wrote a small function to expose bookmarks through lib-voyager) but he's still ramping up in the code base and is a bit swamped with other activities, so it wouldn't be completed very quickly. Feel free to try to do a PR if you need it urgently -- otherwise, I'll add it to our todo list.

**Comment by felixcodes** [comment]
I think it would something like `selectMainSpec(fromSerializable(getApplicationState()))` in `lib-voyager.tsx`
