### ISSUE TITLE
Pass functions to Voyager for customize

### ISSUE THREAD

**Issue by zzhangjii** [vega/voyager#763]
I'm currently working on implementing voyager as data-exploration tool for JupyterLab (JupyterLab_Voyager project), and feels that it would be nice if user can pass some personalized functions to Voyager: 

in  CreateVoyager(container: Container, config: VoyagerConfig, data: Data) function, we can **add one optional parameter**: functions.  User can choose to **pass some function** when creating a voyager. For each function, **an additional button will appear on the view-panel** (specified view or related views), by clicking on it, it runs the function user passed in.

It will bring more freedom to customize. ex: issue 730 (export a visualization) don't have to be s static build-in method, it can be passed in by the users depending on their needs.

**Comment by ssharif6** [comment]
Hi @zzhangjii!

The team discussed this issue and we agreed that we should not necessarily allow for any arbitrary function be passed in. Feel free to let us know which specific methods you need, though, and we can export them through the lib-voyager API.

**Comment by kanitw** [comment]
> we should not allow for any arbitrary function be passed in. 

To clarify, we want to understand the use cases for the function to be passed in first instead of allowing any arbitrary function to be passed in.    

For example, if you only think about export functionality, we can provide API for passing in one or a few "export" behavior so we can have an icon button that's better design specifically for "export" actions.

**Comment by zzhangjii** [comment]
You guys made a fair point! Thx
